[package]
name = "OCReceipt"
version = "0.1.0"
edition = "2021"

[dependencies]
image = {version = "0.25.2", features = ["png", "jpeg"], default-features = false}

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "contrast"
harness = false

[profile.release]
#lto = true

